# Generated by Django 4.1.1 on 2022-09-27 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('rol', models.CharField(max_length=50, verbose_name='Rol')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('cellphone', models.CharField(max_length=30, verbose_name='Cellphone')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('relationship', models.CharField(max_length=50, verbose_name='Relationship')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('oximetry', models.IntegerField(default=0, verbose_name='Oximetry')),
                ('breathing_frequency', models.IntegerField(default=0, verbose_name='Breathing Frequency')),
                ('heart_rate', models.IntegerField(default=0, verbose_name='Heart Rate')),
                ('temperature', models.IntegerField(default=0, verbose_name='Temperature')),
                ('blood_pressure', models.IntegerField(default=0, verbose_name='Blood Pressure')),
                ('blood_glucose', models.IntegerField(default=0, verbose_name='Blood Glucose')),
                ('diagnosis', models.CharField(max_length=50, verbose_name='Diagnosis')),
                ('treatment', models.CharField(max_length=50, verbose_name='Treatment')),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('specialty', models.CharField(max_length=50, verbose_name='Specialty')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('assistant', models.BooleanField(default=False, verbose_name='Assistant')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='appHospital.family')),
                ('history_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='appHospital.history')),
                ('medical_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='appHospital.medical')),
                ('nurse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='appHospital.nurse')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('notas', models.CharField(max_length=50, verbose_name='Notas')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
