# Generated by Django 4.1.1 on 2022-09-27 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliar',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auxiliar',
            name='notas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auxiliar',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='relationship',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='family',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='history',
            name='blood_glucose',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='blood_pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='breathing_frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='diagnosis',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='history',
            name='heart_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='oximetry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='treatment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medical',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medical',
            name='specialty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medical',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='assistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='family_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHospital.family'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='history_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHospital.history'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHospital.medical'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nurse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHospital.nurse'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
