# Generated by Django 4.1.1 on 2022-09-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0002_alter_auxiliar_id_alter_auxiliar_notas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auxiliar',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='medical',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='nurse',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='family_id',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='history_id',
            new_name='history',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='medical_id',
            new_name='medical',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='nurse_id',
            new_name='nurse',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user_id',
            new_name='user',
        ),
    ]
