# Generated by Django 4.1.1 on 2022-09-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0003_rename_user_id_auxiliar_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
